<a href="https://colab.research.google.com/github/jorgejoshuatt/TratamientoDatosPython/blob/main/TratamientoDatosPython/Complementos/01NumpyIntroduccion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

JORGE JOSHUA TREJO MARTINEZ

In [ ]:
"""
Si no existe la libreria la instalamos
!pip install numpy
"""


In [ ]:
import numpy as np

In [ ]:
lista=[1,2,3]
arreglo=np.array(lista)
print(lista)
print(arreglo)

[1, 2, 3]
[1 2 3]


In [ ]:
print(type(lista))
print(type(arreglo))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#Shape 
arreglo.shape

(3,)

In [ ]:
a=np.array([(1,2,3),(4,5,5)])
a

array([[1, 2, 3],
       [4, 5, 5]])

In [ ]:
b=np.array((1,2,3))
b

array([1, 2, 3])

In [ ]:
a.shape

(2, 3)

In [ ]:
#Iterar un arreglo numpy
for i in arreglo:
    print('Valor: {},tipo: {}'.format(i,type(i)))

Valor: 1,tipo: <class 'numpy.int32'>
Valor: 2,tipo: <class 'numpy.int32'>
Valor: 3,tipo: <class 'numpy.int32'>


In [ ]:
c=np.array(['c',3,(12,6,True)],dtype=object)
c

array(['c', 3, (12, 6, True)], dtype=object)

In [ ]:
#Iterar un arreglo numpy
for i in c:
    print('Valor: {},tipo: {}'.format(i,type(i)))

Valor: c,tipo: <class 'str'>
Valor: 3,tipo: <class 'int'>
Valor: (12, 6, True),tipo: <class 'tuple'>


In [ ]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(y.shape)
print(y.ndim)
print(y.size)

(3, 3)
2
9


In [ ]:
#Arreglo tridimensional
t=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])

t

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
print(t.shape)
print(t.ndim)
print(t.size)

(2, 2, 2)
3
8


In [ ]:
#Tipo Float
f=np.array(((11.0,2),(15.0,43)))
print(f)
print(f.dtype)

[[11.  2.]
 [15. 43.]]
float64


In [ ]:
#Tipo Byte
b=np.array(((101,-256),(101,255)),dtype=np.byte)
print(b)
print(b.dtype)

[[101   0]
 [101  -1]]
int8


In [ ]:
#Tipos complejos
c=np.array([[25.6j,11.24],[-21.890-15702174.43j,0]])

print(c)
print(c.dtype)

[[  0.  +2.56000000e+01j  11.24+0.00000000e+00j]
 [-21.89-1.57021744e+07j   0.  +0.00000000e+00j]]
complex128


In [ ]:
#Tipos booleanos
bo=np.array(((1,'Hola'),(False,0)),dtype=np.bool_)
print(bo)
print(bo.dtype)

[[ True  True]
 [False False]]
bool


In [ ]:
#String
print(np.array((['Manzana', 'Naranja'],['Fresa Nacional', 'Uva']))
)

np.array((['Manzana', 'Naranja'],['Fresa Nacional', 'Uva'])).dtype


[['Manzana' 'Naranja']
 ['Fresa Nacional' 'Uva']]


dtype('<U14')

In [ ]:
print(np.array((['Manzana', 'Naranja'],['Fresa Nacional', 'Uva']),dtype=np.string_))
print(np.array((['Manzana', 'Naranja'],['Fresa Nacional', 'Uva']),dtype=np.string_).dtype)

[[b'Manzana' b'Naranja']
 [b'Fresa Nacional' b'Uva']]
|S14


In [ ]:
#Fecha
from datetime import datetime
fechas = np.array([[np.datetime64("2020-08-25T23:59:45.231"), np.datetime64("2021-07-23")], [np.datetime64(datetime(year=2020, month=12, day=22)), np.datetime64("2020-03-01T11:25")]])
print(fechas)
print(fechas.dtype)
print(fechas.shape)

[['2020-08-25T23:59:45.231000' '2021-07-23T00:00:00.000000']
 ['2020-12-22T00:00:00.000000' '2020-03-01T11:25:00.000000']]
datetime64[us]
(2, 2)


In [ ]:
#Operaciones con arreglos
arreglo

array([1, 2, 3])

In [ ]:
arreglo*100

array([100, 200, 300])

In [ ]:
n=np.array(([1,0],[-1,1]))
n

array([[ 1,  0],
       [-1,  1]])

In [ ]:
n+1.5

array([[2.5, 1.5],
       [0.5, 2.5]])

##Equipos

||Equipo 1| Equipo 2|
|:--:|:---:|:---:|
|**Lunes**|Juan, Olga, Alejandra|Alonso, Jorge, Salvador|
|**Martes**|Oscar, Julian, Alejandra|Arturo, Irene, Esteban|
|**Miércoles**|Arturo, Alejandra, Lucio|Jorge, Marco, Juan|
|**Jueves**|Alonso, Julian, Salvador|Alejandra, Jorge, Esteban|
|**Viernes**|Lucio, Irene, Joaquín|Alejandra, Marco, Juan|


In [ ]:
equipos=np.array([[['Juan', 'Olga', 'Alejandra'], ['Alonso', 'Jorge', 'Salvador']],
                    [['Oscar', 'Julian', 'Alejandra'], ['Arturo', 'Irene', 'Esteban']],
                    [['Arturo', 'Alejandra', 'Lucio'], ['Jorge', 'Marco', 'Juan']],
                    [['Alonso', 'Julian', 'Salvador'], ['Alejandra', 'Jorge', 'Esteban']],
                    [['Lucio', 'Irene', 'Joaquín'], ['Alejandra', 'Marco', 'Juan']]])

equipos

array([[['Juan', 'Olga', 'Alejandra'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Oscar', 'Julian', 'Alejandra'],
        ['Arturo', 'Irene', 'Esteban']],

       [['Arturo', 'Alejandra', 'Lucio'],
        ['Jorge', 'Marco', 'Juan']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Alejandra', 'Jorge', 'Esteban']],

       [['Lucio', 'Irene', 'Joaquín'],
        ['Alejandra', 'Marco', 'Juan']]], dtype='<U9')

In [ ]:
print(equipos.ndim)
print(equipos.shape)
print(equipos.size)

3
(5, 2, 3)
30


In [ ]:
#Slide de arreglo
#Ver los equipos del miercoles

print(equipos[2:3])
print(equipos[2:3].shape)

[[['Arturo' 'Alejandra' 'Lucio']
  ['Jorge' 'Marco' 'Juan']]]
(1, 2, 3)


In [ ]:
#Ver los equipos 2 del miercoles
print(equipos[2:3,1])
print(equipos[2:3,1].shape)

[['Jorge' 'Marco' 'Juan']]
(1, 3)


In [ ]:
#Ver los dos primeros integrantes del equipo 2
equipos[:,1,0:2]

array([['Alonso', 'Jorge'],
       ['Arturo', 'Irene'],
       ['Jorge', 'Marco'],
       ['Alejandra', 'Jorge'],
       ['Alejandra', 'Marco']], dtype='<U9')

In [ ]:
#Ver el segundo integrante del equipo1 del viernes
print(equipos[4,0,1])
print(type(equipos[4,0,1]))
print(equipos[4,0,1].shape)


Irene
<class 'numpy.str_'>
()


|Equipo 1| Equipo 2|
:---:|:---:|
|Johnatan, Ringo, Paula|Kenia, Miguel, Carlos|


In [ ]:
reemplazos=np.array([['Johnatan', 'Ringo', 'Paula'], 
               ['Kenia', 'Miguel', 'Carlos']])

reemplazos

array([['Johnatan', 'Ringo', 'Paula'],
       ['Kenia', 'Miguel', 'Carlos']], dtype='<U8')

In [ ]:
print(equipos.shape)
print(reemplazos.shape)

(5, 2, 3)
(2, 3)


In [ ]:
#Equipos del viernes
equipos[4]

array([['Lucio', 'Irene', 'Joaquín'],
       ['Alejandra', 'Marco', 'Juan']], dtype='<U9')

In [ ]:
#Reemplazar equipos del viernes
equipos[4]=reemplazos
equipos[4]


array([['Johnatan', 'Ringo', 'Paula'],
       ['Kenia', 'Miguel', 'Carlos']], dtype='<U9')

In [ ]:
#Equipo2 del martes
equipos[1,1]

array(['Arturo', 'Irene', 'Esteban'], dtype='<U9')

In [ ]:
#Reemplazar por nuevos valores
equipos[1,1]=['Patricia','Genaro','Lucia']
equipos[1,1]

array(['Patricia', 'Genaro', 'Lucia'], dtype='<U9')

In [ ]:
#Primeros 2 integrantes del equipo 1 del jueves
equipos[3,0,0:2]

array(['Alonso', 'Julian'], dtype='<U9')

In [ ]:
#Reemplazar a los Primeros 2 integrantes del equipo 1 del jueves
equipos[3,0,0:2]=['Amanda','Julieta']
equipos[3,0,0:2]

array(['Amanda', 'Julieta'], dtype='<U9')

In [ ]:
#ndarray genera arreglos sin un tipo de datos definidos
np.ndarray((2,2), dtype=np.float_)

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306,             nan]])

In [ ]:
#ones genera un arreglo llenado con 1s
np.ones((2,3,3,6))

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]]])

In [ ]:
#zeros genera un arreglo llenado con 0s
np.zeros((3,3),dtype=np.bool_)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
#arange genera un arreglo con valores definidos en un rango
#arange(<inicio>,<fin>,<incremento> dtype)
np.arange(3,20,3)

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
np.arange(-0.3,1.0,.2)

array([-0.3, -0.1,  0.1,  0.3,  0.5,  0.7,  0.9])

In [ ]:
#linspace genera un arreglo unidimensional con una secuencia lineal de numeros dentro de un rango
#linspace(<inicio>,<fin>,num=<segmentos> dtype)
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
#Copiar un arreglo
a1=np.linspace(0,1,20)
a1
a2=np.copy(a1)

In [ ]:
#Escribir un arreglo en un archivo de texto
#savetxt()
np.savetxt('a1.txt',a1)

In [ ]:
a3=np.ndarray((2,2), dtype=np.float_)
np.savetxt('a3.txt',a3, delimiter='|')

In [ ]:
#Lista el contenido de un directorio desde python
%ls

 El volumen de la unidad C no tiene etiqueta.
 El n�mero de serie del volumen es: FE36-3AF8

 Directorio de c:\Users\jorge\Documents\escuela\Intersemestralpython

26/01/2022  10:27 a. m.    <DIR>          .
26/01/2022  10:27 a. m.    <DIR>          ..
25/01/2022  11:42 a. m.    <DIR>          .vscode
25/01/2022  01:13 p. m.             9,393 03Diccionarios.ipynb
25/01/2022  01:13 p. m.            18,445 04NumpyIntroduccion.ipynb
26/01/2022  10:25 a. m.               520 a1.txt
26/01/2022  10:29 a. m.               106 a3.txt
25/01/2022  01:28 p. m.            94,311 evidencia1.pdf
               5 archivos        122,775 bytes
               3 dirs  812,865,540,096 bytes libres


In [ ]:
#Ver el contenido de un archio desde python
%more a3.txt

6.230420704259777784e-307|4.672967463650385153e-307
1.691210955371402370e-306|1.224399860433020584e-311


In [ ]:
from os import system
#save() Guarda un arreglo en formato binario con la extensión .npy
np.save('a3',a3)
%more a3.npy

“NUMPYv{'descr': '<f8', 'fortran_order': False, 'shape': (2, 2), }                                                          
\??\C:\UsersA

In [ ]:
# loadtxt lee un arreglo desde un archivo de texto
np.loadtxt('a3.txt', delimiter='|')

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.22439986e-311]])

In [ ]:
# load lee un arreglo desde un archivo binario
np.load('a3.npy')

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.22439986e-311]])

In [ ]:
#savez guarda más de un arreglo en un archivo en formato binario
np.savez('arreglos',a1,a3)

In [ ]:
%more arreglos.npz

PK!SxO  	arr_0.npy  “NUMPYv{'descr': '<f8', 'fortran_order': False, 'shape': (20,), }                                                           
(¯¡¼†òª?(¯¡¼†òº?^Cy
å5Ä?(¯¡¼†òÊ?y
å5”×Ð?^Cy
å5Ô?Cy
å5”×?(¯¡¼†òÚ?
å5”×PÞ?y
å5”×à?l(¯¡¼†â?^Cy
å5ä?P^Cy
åå?Cy
å5”ç?6”×P^Cé?(¯¡¼†òê?Êk(¯¡ì?
å5”×Pî?ð?PK!Xþ+'  	arr_1.npy  “NUMPYv{'descr': '<f8', 'fortran_order': False, 'shape': (2, 2), }                                                          
\??\C:\UsersAPK!SxO  	€arr_0.npyPK!Xþ+'  	€[arr_1.npyPKn6

In [ ]:
ac=np.load('arreglos.npz')
ac

In [ ]:
ac['arr_0']

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
ac['arr_1']

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.22439986e-311]])