<a href="https://colab.research.google.com/github/jorgejoshuatt/TratamientoDatosPython/blob/main/dia2y3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conceptos básicos de *Numpy*

[*Numpy*](http://www.numpy.org/) es un paquete que contiene una biblioteca de recursos especializados en realizar operaciones optimizadas en arreglos de datos.

El proyecto *Numpy* cuenta con una extensa documentación, la cual está disponible en https://docs.scipy.org/doc/numpy/.


In [ ]:
# Instalacion del Paquete
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# Importar el paquete numpy
import numpy as np

In [ ]:
arreglo = np.array((1,2,3))
arreglo

array([1, 2, 3])

In [ ]:
type(arreglo)

numpy.ndarray

In [ ]:
for i in arreglo:
  print('Valor: {}, Tipo: {}'.format(i,type(i)))

Valor: 1, Tipo: <class 'numpy.int64'>
Valor: 2, Tipo: <class 'numpy.int64'>
Valor: 3, Tipo: <class 'numpy.int64'>


In [ ]:
arreglo = np.array((1,2,3.5))
print(arreglo)
print(type(arreglo))
for i in arreglo:
  print('Valor: {}, Tipo: {}'.format(i,type(i)))

[1.  2.  3.5]
<class 'numpy.ndarray'>
Valor: 1.0, Tipo: <class 'numpy.float64'>
Valor: 2.0, Tipo: <class 'numpy.float64'>
Valor: 3.5, Tipo: <class 'numpy.float64'>


In [ ]:
arreglo = np.array(['d', 3 , (12, 6, True)], dtype = object)
for i in arreglo:
  print('Valor: {}, Tipo: {}'.format(i,type(i)))

Valor: d, Tipo: <class 'str'>
Valor: 3, Tipo: <class 'int'>
Valor: (12, 6, True), Tipo: <class 'tuple'>


### El atributo ```shape```.

Los arreglos cuentan con el atributo ```shape```, el cual describe el número de elementos que contiene cada dimensión del arreglo.

El valor de ```shape``` es un objeto tipo tuple que contiene una sucesión de números.

```
(<n1>, <n2>, <n3> ... <nm>)
```

* Donde ```<n1>``` corresponde al número de elementos en la primera dimensión,  ```<n2>``` corresponde al número de elementos en la segunda dimensión y así sucesivamente hasta ```<nm>``` , la cual corrersponde al número de elementos de la dimensión ```m```.


In [ ]:
arreglo = np.array((1,2,3.5))
print(arreglo.ndim)     #Numero de Dimenciones
print(arreglo.shape)    #Numero de Elementos en cada Dimencion
print(arreglo.size)     #Numero Total de Elementos en el Arreglo

1
(3,)
3


In [ ]:
#Arreglo Bidimencional
arreglo = np.array([[1, 2, 3],
                    [4, 5, 6]])
print(arreglo.ndim)     #Numero de Dimenciones
print(arreglo.shape)    #Numero de Elementos en cada Dimencion
print(arreglo.size)     #Numero Total de Elementos en el Arreglo

2
(2, 3)
6


In [ ]:
#Arreglo Tridimencional
arreglo = np.array([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]])
print(arreglo.ndim)     #Numero de Dimenciones
print(arreglo.shape)    #Numero de Elementos en cada Dimencion
print(arreglo.size)     #Numero Total de Elementos en el Arreglo
print(arreglo)

3
(2, 2, 2)
8
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
np.array(((1, 2), (3, 4)))
#np.array(((1, 2), (3, 4))).shape

array([[1, 2],
       [3, 4]])

In [ ]:
#Tipo por Default
np.array(((1, 2), (3, 4))).dtype

dtype('int64')

In [ ]:
np.array(((-1, 2), (3, 4)), dtype = np.uint8)

array([[255,   2],
       [  3,   4]], dtype=uint8)

In [ ]:
np.array(((-1, 2), (3, 4)), dtype = np.uint64)

array([[18446744073709551615,                    2],
       [                   3,                    4]], dtype=uint64)

In [ ]:
#Tipos Complejos
complejo = np.array([[25.6j, 11.24],
                      [-21.890-15702174.43j, 0]])
print(complejo)
print(complejo.dtype)

[[  0.  +2.56000000e+01j  11.24+0.00000000e+00j]
 [-21.89-1.57021744e+07j   0.  +0.00000000e+00j]]
complex128


In [ ]:
np.array(((1,'Hola'), (False, 0)))

array([['1', 'Hola'],
       ['False', '0']], dtype='<U21')

In [ ]:
#Arreglo Booleano
np.array(((1,'Hola'), (False, 0)), dtype = np.bool_)

array([[ True,  True],
       [False, False]])

In [ ]:
#Tipo Cadena
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']))

array([['Hugo', 'Paco'],
       ['Luis Ignacio', 'Donald']], dtype='<U12')

In [ ]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = np.string_)

array([[b'Hugo', b'Paco'],
       [b'Luis Ignacio', b'Donald']], dtype='|S12')

In [ ]:
#Trabajo con Fechas
from datetime import datetime
fechas = np.array([[np.datetime64("2019-08-25T23:59:45.231"), 
                   np.datetime64("2020-07-23")],
                   [np.datetime64(datetime(year=2018, month=12, day=22)),
                   np.datetime64("2019-03-01T11:25")]])
fechas

array([['2019-08-25T23:59:45.231000', '2020-07-23T00:00:00.000000'],
       ['2018-12-22T00:00:00.000000', '2019-03-01T11:25:00.000000']],
      dtype='datetime64[us]')

In [ ]:
#DeltaTime los segundos en un lapso de tiempo

np.datetime64(datetime.now()) - fechas

array([[ 89649941798693,  60965127029693],
       [110990727029693, 104988027029693]], dtype='timedelta64[us]')

In [ ]:
a1 = np.array([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]])

a2 = np.array([[[10, 20], [30, 40]],
                    [[50, 60], [70, 80]]])

a3 = np.array((100, 200))

print(a1 + a2)
print('')
print(a1 * 101)
print('')
print(a1 * a3)

[[[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]

[[[101 202]
  [303 404]]

 [[505 606]
  [707 808]]]

[[[ 100  400]
  [ 300  800]]

 [[ 500 1200]
  [ 700 1600]]]


In [ ]:
#ndarray Regresa un Arreglo con Valores no Definidos cercanos a 0
np.ndarray((2,2), dtype=float)

array([[4.42929564e-310, 3.01207749e-310],
       [5.48367052e-310, 5.18709774e-310]])

In [ ]:
np.ndarray((2,2), dtype='>U10')

array([['', ''],
       ['', '']], dtype='>U10')

In [ ]:
#ones Genera un Arreglo Exclusivamente con el Numero 1 en cada Elemento
np.ones((2, 5, 3, 6))

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],


In [ ]:
#zeros Genera un Arreglo Exclusivamente con el Numero 0 en cada Elemento
np.zeros((2, 5, 3, 6))

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],


In [ ]:
np.zeros((2, 2, 2), dtype=bool)

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [ ]:
np.ones((2, 2, 2), dtype=bool)

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [ ]:
#empty Genera Arreglos Vacios
np.empty((2, 2, 2), dtype=np.int8)

array([[[ 96,  50],
        [-11,   2]],

       [[  0,   0],
        [  0,   0]]], dtype=int8)

In [ ]:
#arange Genera un Arreglo Unidimencional con Valores Enteros en un Rango
np.arange(6,21)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
#arange(Limite Inferior, Limite Superior, Salto)
np.arange(-30, 10, 4)

array([-30, -26, -22, -18, -14, -10,  -6,  -2,   2,   6])

In [ ]:
#linspace Genera un Arreglo Unidimencional con una Secuencia Lineal de Valores dentro de un Rango
np.linspace(0,8)

array([0.        , 0.16326531, 0.32653061, 0.48979592, 0.65306122,
       0.81632653, 0.97959184, 1.14285714, 1.30612245, 1.46938776,
       1.63265306, 1.79591837, 1.95918367, 2.12244898, 2.28571429,
       2.44897959, 2.6122449 , 2.7755102 , 2.93877551, 3.10204082,
       3.26530612, 3.42857143, 3.59183673, 3.75510204, 3.91836735,
       4.08163265, 4.24489796, 4.40816327, 4.57142857, 4.73469388,
       4.89795918, 5.06122449, 5.2244898 , 5.3877551 , 5.55102041,
       5.71428571, 5.87755102, 6.04081633, 6.20408163, 6.36734694,
       6.53061224, 6.69387755, 6.85714286, 7.02040816, 7.18367347,
       7.34693878, 7.51020408, 7.67346939, 7.83673469, 8.        ])

In [ ]:
np.linspace(0,8, num=100)

array([0.        , 0.08080808, 0.16161616, 0.24242424, 0.32323232,
       0.4040404 , 0.48484848, 0.56565657, 0.64646465, 0.72727273,
       0.80808081, 0.88888889, 0.96969697, 1.05050505, 1.13131313,
       1.21212121, 1.29292929, 1.37373737, 1.45454545, 1.53535354,
       1.61616162, 1.6969697 , 1.77777778, 1.85858586, 1.93939394,
       2.02020202, 2.1010101 , 2.18181818, 2.26262626, 2.34343434,
       2.42424242, 2.50505051, 2.58585859, 2.66666667, 2.74747475,
       2.82828283, 2.90909091, 2.98989899, 3.07070707, 3.15151515,
       3.23232323, 3.31313131, 3.39393939, 3.47474747, 3.55555556,
       3.63636364, 3.71717172, 3.7979798 , 3.87878788, 3.95959596,
       4.04040404, 4.12121212, 4.2020202 , 4.28282828, 4.36363636,
       4.44444444, 4.52525253, 4.60606061, 4.68686869, 4.76767677,
       4.84848485, 4.92929293, 5.01010101, 5.09090909, 5.17171717,
       5.25252525, 5.33333333, 5.41414141, 5.49494949, 5.57575758,
       5.65656566, 5.73737374, 5.81818182, 5.8989899 , 5.97979

In [ ]:
#Escribir en un archivo txt
arreglo = np.linspace(0, 8, num=100)
np.savetxt('arreglo.txt', arreglo)

In [ ]:
#Escribir en un Archivo Binario
np.save('arreglo', arreglo)

In [ ]:
#Leer Archivo
arreglo2 = np.loadtxt('arreglo.txt')
arreglo2

array([0.        , 0.08080808, 0.16161616, 0.24242424, 0.32323232,
       0.4040404 , 0.48484848, 0.56565657, 0.64646465, 0.72727273,
       0.80808081, 0.88888889, 0.96969697, 1.05050505, 1.13131313,
       1.21212121, 1.29292929, 1.37373737, 1.45454545, 1.53535354,
       1.61616162, 1.6969697 , 1.77777778, 1.85858586, 1.93939394,
       2.02020202, 2.1010101 , 2.18181818, 2.26262626, 2.34343434,
       2.42424242, 2.50505051, 2.58585859, 2.66666667, 2.74747475,
       2.82828283, 2.90909091, 2.98989899, 3.07070707, 3.15151515,
       3.23232323, 3.31313131, 3.39393939, 3.47474747, 3.55555556,
       3.63636364, 3.71717172, 3.7979798 , 3.87878788, 3.95959596,
       4.04040404, 4.12121212, 4.2020202 , 4.28282828, 4.36363636,
       4.44444444, 4.52525253, 4.60606061, 4.68686869, 4.76767677,
       4.84848485, 4.92929293, 5.01010101, 5.09090909, 5.17171717,
       5.25252525, 5.33333333, 5.41414141, 5.49494949, 5.57575758,
       5.65656566, 5.73737374, 5.81818182, 5.8989899 , 5.97979

In [ ]:
#Listar el Contenido de
%ls

arreglo.npy  arreglo.txt  sample_data/


In [ ]:
#Ver el Contenido de un Archivo
%cat arreglo.txt

0.000000000000000000e+00
8.080808080808081495e-02
1.616161616161616299e-01
2.424242424242424310e-01
3.232323232323232598e-01
4.040404040404040886e-01
4.848484848484848619e-01
5.656565656565657463e-01
6.464646464646465196e-01
7.272727272727272929e-01
8.080808080808081773e-01
8.888888888888889506e-01
9.696969696969697239e-01
1.050505050505050608e+00
1.131313131313131493e+00
1.212121212121212155e+00
1.292929292929293039e+00
1.373737373737373924e+00
1.454545454545454586e+00
1.535353535353535470e+00
1.616161616161616355e+00
1.696969696969697017e+00
1.777777777777777901e+00
1.858585858585858785e+00
1.939393939393939448e+00
2.020202020202020332e+00
2.101010101010101216e+00
2.181818181818182101e+00
2.262626262626262985e+00
2.343434343434343425e+00
2.424242424242424310e+00
2.505050505050505194e+00
2.585858585858586078e+00
2.666666666666666963e+00
2.747474747474747847e+00
2.828282828282828731e+00
2.909090909090909172e+00
2.989898989898990056e+00
3.070707070707070940e+00
3.151515151515151825e+00


In [ ]:
np.load('arreglo.npy')

array([0.        , 0.08080808, 0.16161616, 0.24242424, 0.32323232,
       0.4040404 , 0.48484848, 0.56565657, 0.64646465, 0.72727273,
       0.80808081, 0.88888889, 0.96969697, 1.05050505, 1.13131313,
       1.21212121, 1.29292929, 1.37373737, 1.45454545, 1.53535354,
       1.61616162, 1.6969697 , 1.77777778, 1.85858586, 1.93939394,
       2.02020202, 2.1010101 , 2.18181818, 2.26262626, 2.34343434,
       2.42424242, 2.50505051, 2.58585859, 2.66666667, 2.74747475,
       2.82828283, 2.90909091, 2.98989899, 3.07070707, 3.15151515,
       3.23232323, 3.31313131, 3.39393939, 3.47474747, 3.55555556,
       3.63636364, 3.71717172, 3.7979798 , 3.87878788, 3.95959596,
       4.04040404, 4.12121212, 4.2020202 , 4.28282828, 4.36363636,
       4.44444444, 4.52525253, 4.60606061, 4.68686869, 4.76767677,
       4.84848485, 4.92929293, 5.01010101, 5.09090909, 5.17171717,
       5.25252525, 5.33333333, 5.41414141, 5.49494949, 5.57575758,
       5.65656566, 5.73737374, 5.81818182, 5.8989899 , 5.97979

# Operaciones básicas con arreglos.


La siguiente tabla ejemplifica la conformación de las Equipos en una semana dada.

||Equipo 1| Equipo 2|
|:--:|:---:|:---:|
|**Lunes**|Lilia, Antonio, Ricardo|Alonso, Jorge, Salvador|
|**Martes**|Mariana, Julian, Ricardo|Arturo, Ramy, Esteban|
|**Miércoles**|Arturo, Ricardo, Lucio|Jorge, Marco, Lilia|
|**Jueves**|Alonso, Julian, Salvador|Ricardo, Jorge, Esteban|
|**Viernes**|Lucio, Ramy, Joaquín|Ricardo, Marco, Lilia|


In [ ]:
equipos = np.array([[['Lilia', 'Antonio', 'Ricardo'], ['Alonso', 'Jorge', 'Salvador']],
                    [['Mariana', 'Julian', 'Ricardo'], ['Arturo', 'Ramy', 'Esteban']],
                    [['Arturo', 'Ricardo', 'Lucio'], ['Jorge', 'Marco', 'Lilia']],
                    [['Alonso', 'Julian', 'Salvador'], ['Ricardo', 'Jorge', 'Esteban']],
                    [['Lucio', 'Ramy', 'Joaquín'], ['Ricardo', 'Marco', 'Lilia']]])

In [ ]:
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Lucio', 'Ramy', 'Joaquín'],
        ['Ricardo', 'Marco', 'Lilia']]], dtype='<U8')

In [ ]:
print(equipos.ndim)
print(equipos.shape)
print(equipos.size)

3
(5, 2, 3)
30


In [ ]:
#Slice de Arreglos
#Listar los Dias Martes y Miercoles de la Semana
equipos[1:3]

array([[['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']]], dtype='<U8')

In [ ]:
equipos[1:3].shape

(2, 2, 3)

In [ ]:
#Ver el Equipo 2 de los Dias Martes y Miercoles de la Semana
equipos[1:3, 1]

array([['Arturo', 'Ramy', 'Esteban'],
       ['Jorge', 'Marco', 'Lilia']], dtype='<U8')

In [ ]:
equipos[1:3, 1].shape

(2, 3)

In [ ]:
#Ver los 2 Primeros Integrantes del Equipo 2 de los Dias Martes y Miercoles de la Semana
equipos[1:3, 1, 0:2]

array([['Arturo', 'Ramy'],
       ['Jorge', 'Marco']], dtype='<U8')

In [ ]:
equipos[1:3, 1, 0:2].shape

(2, 2)

In [ ]:
#Ver el Tercer Integrante del Equipo 1 en todos los Dias
equipos[:, 0, 2:3]

array([['Ricardo'],
       ['Ricardo'],
       ['Lucio'],
       ['Salvador'],
       ['Joaquín']], dtype='<U8')

In [ ]:
#Ver el Integrante 3 del Equipo 2 del Viernes
equipos[4, 1, 2]

'Lilia'

In [ ]:
print(type(equipos[4, 1, 2]))
print(equipos[4, 1, 2].shape)
print(equipos[4, 1, 2].size)

<class 'numpy.str_'>
()
1


#Remplazos
|Equipo 1| Equipo 2|
:---:|:---:|
|Paulina, Rigo, Paul|Kenia, Miguel, Carlos|


In [ ]:
remplazos = np.array([['Paulina', 'Rigo', 'Paul'], 
               ['Kenia', 'Miguel', 'Carlos']])
remplazos

array([['Paulina', 'Rigo', 'Paul'],
       ['Kenia', 'Miguel', 'Carlos']], dtype='<U7')

In [ ]:
remplazos.shape

(2, 3)

In [ ]:
equipos[4]

array([['Lucio', 'Ramy', 'Joaquín'],
       ['Ricardo', 'Marco', 'Lilia']], dtype='<U8')

In [ ]:
equipos[4].shape

(2, 3)

In [ ]:
#Cambiar Elementos de un Arreglo
equipos[4] = remplazos
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Paulina', 'Rigo', 'Paul'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [ ]:
#Cambiar 2 Elementos de un Arreglo
equipos[2, 0, 0:2] = ['Julio', 'Ernesto']
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Julio', 'Ernesto', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Paulina', 'Rigo', 'Paul'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [ ]:
#Cambiar un Solo Elemento
equipos[3, 1, 2] = 'Esmeralda'
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Julio', 'Ernesto', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esmerald']],

       [['Paulina', 'Rigo', 'Paul'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [ ]:
#Es posible identificar Elementos de una Dimencion usando Arreglos como Indices
idx_1 = np.array([2, 0, 3])
print(idx_1)
print(equipos[idx_1])

[2 0 3]
[[['Julio' 'Ernesto' 'Lucio']
  ['Jorge' 'Marco' 'Lilia']]

 [['Lilia' 'Antonio' 'Ricardo']
  ['Alonso' 'Jorge' 'Salvador']]

 [['Alonso' 'Julian' 'Salvador']
  ['Ricardo' 'Jorge' 'Esmerald']]]


In [ ]:
idx_2 = np.array([[ 0, 3], [1, 4]])
print(idx_2)
print(equipos[idx_2])
print(equipos[idx_2].shape)

[[0 3]
 [1 4]]
[[[['Lilia' 'Antonio' 'Ricardo']
   ['Alonso' 'Jorge' 'Salvador']]

  [['Alonso' 'Julian' 'Salvador']
   ['Ricardo' 'Jorge' 'Esmerald']]]


 [[['Mariana' 'Julian' 'Ricardo']
   ['Arturo' 'Ramy' 'Esteban']]

  [['Paulina' 'Rigo' 'Paul']
   ['Kenia' 'Miguel' 'Carlos']]]]
(2, 2, 2, 3)


In [ ]:
#Uso de Multiples Arreglos como Indices
idx_x = np.array([0, 2])  #Lunes y Miercoles
idx_y = np.array([0, 1])  #Equipo 1 y 2
equipos[idx_x, idx_y]

array([['Lilia', 'Antonio', 'Ricardo'],
       ['Jorge', 'Marco', 'Lilia']], dtype='<U8')

#Broadcast


In [ ]:
equipos[4, 0] = 'Fabian'
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Julio', 'Ernesto', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esmerald']],

       [['Fabian', 'Fabian', 'Fabian'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [ ]:
#Un Mismo Arreglo para todos los Elementos de la Dimencion
equipos[2] = np.array(['Hugo', 'Paco', 'Luis'])
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Hugo', 'Paco', 'Luis'],
        ['Hugo', 'Paco', 'Luis']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esmerald']],

       [['Fabian', 'Fabian', 'Fabian'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')